# -*- coding: utf-8 -*-
"""3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15K-d8thoOZl928p6u5z8bhH-tWjqzvP1
"""

def perceptron_decision(hero, heroine, climate, weights, bias):
    inputs = np.array([hero, heroine, climate])
    output = np.dot(weights, inputs) + bias
    return 1 if output >= 0 else 0

# Example usage
weights = np.array([0.5, 0.4, 0.2])
bias = -0.5
hero = 1
heroine = 1
climate = 1
decision = perceptron_decision(hero, heroine, climate, weights, bias)
print("Decision:", decision)

